export const FETCH_USER = "FETCH_USER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const LOGIN_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const LOGIN_USER_FAIL = "CREATE_USER_FAIL"
export const LOGOUT_USER = "LOGOUT_USER"